version: 2.1
jobs:
  build:
    working_directory: ~/super-cool-notebook-app/ui
    docker:
      - image: cimg/node:18.1
    steps:
      - checkout:
          path: ~/super-cool-notebook-app
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test